SELECT NAME,PHONENO 
FROM Student 
WHERE NAME LIKE '_A%' AND ROLLNO IN (SELECT ROLLNO FROM Results WHERE SUB_CODE='CS301');

SELECT MARKS FROM Results 
WHERE ROLLNO IN (SELECT ROLLNO FROM Student WHERE to_char(BIRTHDATE,'MM')='06');

SELECT * FROM Student WHERE DEPTCODE='CSE' AND SEMESTER='SEM5';

SELECT * FROM Subject WHERE DEPTCODE='CSE' AND SEMESTER='SEM3';

SELECT DEPTNAME FROM Department 
WHERE DEPTCODE IN (SELECT DEPTCODE FROM Subject WHERE SUBJECTCODE IN (SELECT
SUBJECTCODE FROM Result WHERE MARKS>90));

SELECT NAME FROM Student 
WHERE SEMESTER='SEM5' AND ROLLNO IN (SELECT ROLLNO FROM Results WHERE MARKS>80);

SELECT NAME FROM Student 
WHERE DEPTCODE='CSE' AND to_char(BIRTHDATE,'YYYY')='2000' AND ROLLNO IN (SELECT
ROLLNO FROM Results WHERE SUB_CODE='CS301' AND MARKS>80);

SELECT * FROM Department 
WHERE STUDENTALLOTED<80 AND DEPTCODE IN (SELECT DEPTCODE FROM Subject WHERE
SUBJECTNAME='Data Communication');

SELECT SUBJECTNAME,SUBJECTCODE FROM Subject 
WHERE DEPTCODE IN (SELECT DEPTCODE FROM Department WHERE
STUDENTALLOTED<100);

SELECT * FROM Results
WHERE SUB_CODE IN (SELECT SUBJECTCODE FROM Subject WHERE DEPTCODE='CSE' AND SEMESTER='SEM5'
AND SUBJECTNAME LIKE 'D%');

SELECT * FROM Results WHERE SUB_CODE='CS505' AND ROLLNO IN (SELECT ROLLNO FROM Student WHERE YEAROFADM=2017);

SELECT * FROM Student WHERE DEPTCODE='CSE' AND ROLLNO NOT IN (SELECT ROLLNO FROM Results);

SELECT SUBJECTNAME,SUBJECTCODE FROM Subject WHERE SUBJECTCODE NOT IN (SELECT SUB_CODE FROM Results  );

